language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  #- "3.8-dev"  # 3.8 development branch
install:
  - pip install -r requirements.txt
script:
  - python setup.py install
  - pytest