version: 2.1

orbs:
  python: circleci/python@1.3.1
  
workflows:
  main:
    jobs:
      - python/test:
          pkg-manager: pip-dist
          args: pytest -r requirements.txt
          test-tool: pytest
